# Valid commModes are only pull or push
CommMode = "push"

# If push mode is specified then following section is mandatory 
[Push]
AgentEndPoint ="http://agent:8080/"

[Check]
Target  = "localhost:3000"
Opts = "{}"
CheckID ="id"

[Log]
LogFmt  =  "text"
LogLevel = "info"

