name: Build

on:
  push:
  pull_request:

jobs:

  build:

    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.19'

      - name: Install tests deps
        run: sudo apt install nmap -y

      - name: Go test
        run: go test ./... -count=1
